# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-27 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0008_auto_20200201_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='view_method',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
