# Generated by Django 3.2.7 on 2021-09-30 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0011_auto_20201117_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='requested_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
    ]
